onEvent('block.registry', event => {
    event.create('crude_controller').material('metal').hardness(2).displayName('Crude Controller').tagBlock('minecraft:mineable/pickaxe')
    event.create('impure_uranium').material('stone').hardness(2).displayName('Impure Uranium').tagBlock('minecraft:mineable/pickaxe')
    
    event.create('mossy_seared_bricks').material('stone').hardness(3).resistance(9).displayName('Mossy Seared Bricks')
        .tagBlock('minecraft:mineable/pickaxe')
        //.tagBoth("tconstruct:seared_blocks")
        .tagBlock("forge:needs_gold_tool")
        .tagBlock("twilight:mossy_seared_blocks")
        //.tagItem("tconstruct:smeltery")

    event.create('mossy_seared_cobble').material('stone').hardness(3).resistance(9).displayName('Mossy Seared Cobblestone')
        .tagBlock('minecraft:mineable/pickaxe')
        //.tagBoth("tconstruct:seared_blocks")
        .tagBlock("forge:needs_gold_tool")
        .tagBoth("twilight:mossy_seared_blocks")
        //.tagItem("tconstruct:smeltery")

    event.create('mossy_seared_cracked_bricks').material('stone').hardness(3).resistance(9).displayName('Mossy Seared Cracked Bricks')
        .tagBlock('minecraft:mineable/pickaxe')
        //.tagBoth("tconstruct:seared_blocks")
        .tagBlock("forge:needs_gold_tool")
        .tagBoth("twilight:mossy_seared_blocks")
        //.tagItem("tconstruct:smeltery")

    event.create('mossy_seared_fancy_bricks').material('stone').hardness(3).resistance(9).displayName('Mossy Fancy Seared Bricks')
        .tagBlock('minecraft:mineable/pickaxe')
        //.tagBoth("tconstruct:seared_blocks")
        .tagBlock("forge:needs_gold_tool")
        .tagBoth("twilight:mossy_seared_blocks")
        //.tagItem("tconstruct:smeltery")

    event.create('mossy_seared_stone').material('stone').hardness(3).resistance(9).displayName('Mossy Seared Stone')
        .tagBlock('minecraft:mineable/pickaxe')
        //.tagBoth("tconstruct:seared_blocks")
        .tagBlock("forge:needs_gold_tool")
        .tagBoth("twilight:mossy_seared_blocks")
        //.tagItem("tconstruct:smeltery")
    
    event.create('mossy_seared_paver').material('stone').hardness(3).resistance(9).displayName('Mossy Seared Paver')
        .tagBlock('minecraft:mineable/pickaxe')
        //.tagBoth("tconstruct:seared_blocks")
        .tagBlock("forge:needs_gold_tool")
        .tagBoth("twilight:mossy_seared_blocks")
        //.tagItem("tconstruct:smeltery")

    event.create('mossy_seared_triangle_bricks').material('stone').hardness(3).resistance(9).displayName('Mossy Seared Triangle Bricks')
        .tagBlock('minecraft:mineable/pickaxe')
        //.tagBoth("tconstruct:seared_blocks")
        .tagBlock("forge:needs_gold_tool")
        .tagBoth("twilight:mossy_seared_blocks")
        //.tagItem("tconstruct:smeltery")

})